### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by altunyurt** [EmreDereli/infiniteScroll#1]
Is it still responsive when there is a large number of items in the render list? 

For example, if the user is at the 250th page and keeps scrolling, would the app still be responsive? 
How would you solve the issue?

**Comment by EmreDereli** [comment]
VirtualizedList should be used if there is a large list. Otherwise we can improve the performance of FlatList. In order to improve, the component that will be rendered should be **PureComponent** or should contain **"shouldComponentUpdate"** method
